get:
  operationId: GetViewsEntityConfigurationsActive
  summary: Get Active View Configuration
  description: >-
    Get the active view configurations for an entity. If no active view is set,
    `null` is returned. An admin user can only retrieve their own active
    configuration.
  x-authenticated: true
  parameters:
    - name: entity
      in: path
      description: >-
        The entity to retrieve its active view configurations (for example,
        `orders`).
      required: true
      schema:
        type: string
    - name: fields
      in: query
      description: >-
        Comma-separated fields that should be included in the returned data. If
        a field is prefixed with `+` it will be added to the default fields,
        using `-` will remove it from the default fields. Without prefix it will
        replace the entire default fields.
      required: false
      schema:
        type: string
        title: fields
        description: >-
          Comma-separated fields that should be included in the returned data.
          If a field is prefixed with `+` it will be added to the default
          fields, using `-` will remove it from the default fields. Without
          prefix it will replace the entire default fields.
        externalDocs:
          url: '#select-fields-and-relations'
  security:
    - api_token: []
    - cookie_auth: []
    - jwt_token: []
  x-codeSamples:
    - lang: Shell
      label: cURL
      source:
        $ref: >-
          ../code_samples/Shell/admin_views_{entity}_configurations_active/get.sh
  tags:
    - Views
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../components/schemas/AdminViewConfigurationResponse.yaml
              - type: object
                description: >-
                  Additional properties related to the active view
                  configuration.
                properties:
                  is_default_active:
                    type: boolean
                    title: is_default_active
                    description: >-
                      Whether the active view configuration is the system
                      default.
                  default_type:
                    type: string
                    description: >-
                      The type of the default view configuration if the active
                      view is the system default. It will be `system` if the
                      active view is the system default, `code` if no active
                      view is set, or `undefined` if the active view isn't the
                      system default.
                    enum:
                      - code
                      - system
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
  x-since: 2.10.3
  x-featureFlag: view_configurations
post:
  operationId: PostViewsEntityConfigurationsActive
  summary: Make View Configuration Active
  description: >-
    Make a view configuration active. This will set the given view configuration
    as the active one for the specified entity for the admin user. An admin user
    can only set their own configurations as active. If the view configuration
    ID is `null`, the active view configuration will be cleared, and the `code`
    or system default view configuration type will be used as the active view.
  x-authenticated: true
  parameters:
    - name: entity
      in: path
      description: The entity to update its view configuration (for example, `orders`).
      required: true
      schema:
        type: string
  security:
    - api_token: []
    - cookie_auth: []
    - jwt_token: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/AdminSetActiveViewConfiguration.yaml
  x-codeSamples:
    - lang: Shell
      label: cURL
      source:
        $ref: >-
          ../code_samples/Shell/admin_views_{entity}_configurations_active/post.sh
  tags:
    - Views
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            description: The details of the operation.
            required:
              - success
            properties:
              success:
                type: boolean
                title: success
                description: Whether the operation was successful.
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
  x-since: 2.10.3
  x-featureFlag: view_configurations
