get:
  operationId: GetViewsEntityConfigurationsId
  summary: Get View Configuration
  description: >-
    Retrieve a view configuration for an entity. An admin user can only retrieve
    their own configurations.
  x-authenticated: true
  parameters:
    - name: entity
      in: path
      description: The entity to retrieve its view configurations (for example, `orders`)
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: The ID of the view configuration to retrieve.
      required: true
      schema:
        type: string
    - name: fields
      in: query
      description: >-
        Comma-separated fields that should be included in the returned data. If
        a field is prefixed with `+` it will be added to the default fields,
        using `-` will remove it from the default fields. Without prefix it will
        replace the entire default fields.
      required: false
      schema:
        type: string
        title: fields
        description: >-
          Comma-separated fields that should be included in the returned data.
          If a field is prefixed with `+` it will be added to the default
          fields, using `-` will remove it from the default fields. Without
          prefix it will replace the entire default fields.
        externalDocs:
          url: '#select-fields-and-relations'
  security:
    - api_token: []
    - cookie_auth: []
    - jwt_token: []
  x-codeSamples:
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/admin_views_{entity}_configurations_{id}/get.sh
  tags:
    - Views
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminViewConfigurationResponse.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
  x-since: 2.10.3
  x-featureFlag: view_configurations
post:
  operationId: PostViewsEntityConfigurationsId
  summary: Update View Configuration
  description: >-
    Update the view configuration of an entity. An admin user can only update
    their own configurations.
  x-authenticated: true
  parameters:
    - name: entity
      in: path
      description: The entity to update its view configuration (for example, `orders`).
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: The view configuration's ID.
      required: true
      schema:
        type: string
  security:
    - api_token: []
    - cookie_auth: []
    - jwt_token: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/AdminUpdateViewConfiguration.yaml
  x-codeSamples:
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/admin_views_{entity}_configurations_{id}/post.sh
  tags:
    - Views
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AdminViewConfigurationResponse.yaml
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
  x-workflow: updateViewConfigurationWorkflow
  x-events: []
  x-since: 2.10.3
  x-featureFlag: view_configurations
delete:
  operationId: DeleteViewsEntityConfigurationsId
  summary: Remove View Configurations
  description: >-
    Remove view configurations of an entity. An admin user can only delete their
    own configurations.
  x-authenticated: true
  parameters:
    - name: entity
      in: path
      description: The entity to delete its view configuration (for example, `orders`)
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: The ID of the view configuration to delete
      required: true
      schema:
        type: string
  security:
    - api_token: []
    - cookie_auth: []
    - jwt_token: []
  x-codeSamples:
    - lang: Shell
      label: cURL
      source:
        $ref: >-
          ../code_samples/Shell/admin_views_{entity}_configurations_{id}/delete.sh
  tags:
    - Views
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            description: The details of the deletion operation.
            required:
              - id
              - object
              - deleted
            properties:
              id:
                type: string
                title: id
                description: The ID of the deleted View Configuration.
              object:
                type: string
                title: object
                description: The name of the deleted object.
                example: view_configuration
              deleted:
                type: boolean
                title: deleted
                description: Whether the view was deleted.
    '400':
      $ref: ../components/responses/400_error.yaml
    '401':
      $ref: ../components/responses/unauthorized.yaml
    '404':
      $ref: ../components/responses/not_found_error.yaml
    '409':
      $ref: ../components/responses/invalid_state_error.yaml
    '422':
      $ref: ../components/responses/invalid_request_error.yaml
    '500':
      $ref: ../components/responses/500_error.yaml
  x-since: 2.10.3
  x-featureFlag: view_configurations
