type: object
description: The details of a view configuration.
x-schemaName: AdminViewConfigurationResponse
required:
  - view_configuration
properties:
  view_configuration:
    $ref: ./AdminViewConfiguration.yaml
