name: k6 Load Test

on:
  workflow_dispatch:
    inputs:
      endpoint:
        description: "Endpoint for performance tests"
        required: true
        default: "https://dtc-starter.medusajs.app"
      region_id:
        description: "Region ID for performance tests"
        required: true
        default: "reg_01K2ZDG12VKJ64F2NFTNW7Y8AT"
      publishable_key:
        description: "Publishable key for performance tests"
        required: true
        default: "pk_937f7a595bd4b039bb6bbb95476dd036dd79187f31ef61cf7093f2b81a1f863b"

jobs:
  run-test:
    runs-on: ubuntu-latest
    env:
      K6_ENDPOINT: ${{ github.event.inputs.endpoint }}
      K6_REGION_ID: ${{ github.event.inputs.region_id }}
      K6_PUBLISHABLE_KEY: ${{ github.event.inputs.publishable_key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: ./scripts/cart-operations.js
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
